use_frameworks!

platform :ios, '10.0'

target 'waldo-app-sdk_Example' do
  pod 'waldo-app-sdk', :path => '../'

  target 'waldo-app-sdk_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end
