name: Build iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    name: Swift ${{ matrix.swift }}
    runs-on: macos-latest
    strategy:
      matrix:
        swift: ["5.7"]

    steps:
      - uses: actions/checkout@v3
      - uses: fwal/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
        with:
          swift-version: ${{ matrix.swift }}
      - name: Build
        working-directory: ./ios
        run: swift build
      - name: Run tests
        working-directory: ./ios
        run: swift test